name: Pre-commit

on: [ push, pull_request ]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files
